### ISSUE TITLE
new dell xps 9550

### ISSUE THREAD

**Issue by lew1s** [the-darkvoid/XPS9530-OSX#10]
can i use this for new dell xps 9950? 

and this guide is with dual boot as well ?

**Comment by nexbit** [comment]
I don't think so.. Sylake isn't well supported yet, especially on laptops.

See http://www.tonymacx86.com/laptop-compatibility/179644-dell-xps-9550-can-install-capitan.html

**Comment by the-darkvoid** [comment]
Correct, Skylake is a different chipset. There are other people who have this device and managed to get it working with Sierra, so follow their guides.
