### ISSUE TITLE
El capitan 10.11.1 iokit patch

### ISSUE THREAD

**Issue by chashmeetsingh** [the-darkvoid/XPS9530-OSX#6]
the iokit patch changes my md5 to 
[IOKit]: Patching IOKit for maximum pixel clock
[IOKit]: Current IOKit md5 is 76bad895d4f5a2d2fa5f4bc0ec23e4e9
         --> Unknown IOKit version (no action taken)
which is not their in the script for patched ones please help

**Comment by AndrejSoroj** [comment]
The same for me. After patching IOKit on 10.11.1, script can't recognize new md5 hash and says:
--> Unknown IOKit version (no action taken)

**Comment by syscl** [comment]
The patch commend is the same as previous, hence you can do it by yourself in Terminal:
sudo perl -i.bak -pe 's|\xB8\x01\x00\x00\x00\xF6\xC1\x01\x0F\x85|\x33\xC0\x90\x90\x90\x90\x90\x90\x90\xE9|sg' /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit
sudo codesign -f -s - /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit

Good luck!

**Comment by chashmeetsingh** [comment]
yes I tried that but when I try to re patch it says unknown iokit version instead of it has already been patched acc to the script

**Comment by syscl** [comment]
Maybe your IOKit has been replaced fo some reasons.

Replacing your IOKit with the origin IOKit from the media you used to install OS X. If the script still shows unknown version, that you really need to re downlaod an unmodified image.

**Comment by chashmeetsingh** [comment]
I had downloaded the .app from app store
I had same issues with 10.11

**Comment by chashmeetsingh** [comment]
@the-darkvoid please help

**Comment by chashmeetsingh** [comment]
i got this 

./XPS9530.sh --patch-iokit
[IOKit]: Patching IOKit for maximum pixel clock
[IOKit]: Current IOKit md5 is 8df7effea833a7d4d243a55d5fdbf946
         --> El Capitan 10.11.1 IOKit (patched)
         IOKit is already patched, no action taken.

**Comment by robvanoostenrijk** [comment]
If for some reason the IOKit version is not recognized you can execute the manual patch commands:

    sudo perl -i.bak -pe 's|\xB8\x01\x00\x00\x00\xF6\xC1\x01\x0F\x85|\x33\xC0\x90\x90\x90\x90\x90\x90\x90\xE9|sg' /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit
    sudo codesign -f -s - /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit

**Comment by chashmeetsingh** [comment]
I used these commands 
everytime I run them they produce a random md5 hash

**Comment by the-darkvoid** [comment]
If for some reason the IOKit version is not recognized you can execute the manual patch commands:

    sudo perl -i.bak -pe 's|\xB8\x01\x00\x00\x00\xF6\xC1\x01\x0F\x85|\x33\xC0\x90\x90\x90\x90\x90\x90\x90\xE9|sg' /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit
    sudo codesign -f -s - /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit

That is possible, due to the self-signed code signing. It should work just fine, finish the guide.

**Comment by chashmeetsingh** [comment]
See i have a lenovo y50-70 uhd 
I have finished following the guide the only thing that is not working is the screen display
When I login the screen goes black and I can't see anything but I can on a monitor , I consulted rehabman he says that everything is patched successfully the reason why the screen does not display will be because of the ioit not being patched correctly please guide

**Comment by the-darkvoid** [comment]
Taking the original IOKit (10.11.1) and running only the perl patch command results in the following differences:
    
    # cmp -l IOKit.bak IOKit
    111257 270  63
    111258   1 300
    111259   0 220
    111260   0 220
    111261   0 220
    111262 366 220
    111263 301 220
    111264   1 220
    111265  17 220
    111266 205 351

Validate that those are the same for you, then only codesign the binary.

**Comment by chashmeetsingh** [comment]
yes got the same result but still I get the black screen which sometimes flickers and shows me the screen

**Comment by the-darkvoid** [comment]
Check if in "System Preferences" -> "Displays" it shows more than one display when you boot with the external display. If it does then the IOKit patch is working fine.

The black screen would then be because of a framebuffer issue, which does seem likely because you are sometimes getting an image.

**Comment by chashmeetsingh** [comment]
yes I get multiple displays but then how to fix the framebuffer issue 

I am currently using this config.plist

https://raw.githubusercontent.com/RehabMan/Lenovo-Y50-DSDT-Patch/master/config_UHD.plist

**Comment by the-darkvoid** [comment]
Try and get the help you require on the tonymacx86.com forums. There is information on the Lenovo Y50 there.

Your IOKit is patched correctly if both displays are showing.
