### ISSUE TITLE
Screen Freezes w/ SSDT-12

### ISSUE THREAD

**Issue by 705369025wu** [the-darkvoid/XPS9530-OSX#8]
Tried to remove the "0x09" "0x04" after all 4 places of "Return (GPRW)" so that it can be compiled by MaciASL
The result of it is panic mode (exit and reboot after a few seconds)
(Boot normally without SSDT-12)

Method (_PRW, 0, NotSerialized)
{
    Return (GPRW)
    0x09
    0x04
}

**Comment by robvanoostenrijk** [comment]
It should not be required to make any changes to compile the SSDT.

**Comment by the-darkvoid** [comment]
It should not be required to make any changes to compile the SSDT.

**Comment by 705369025wu** [comment]
Then is it possible that it have something to do with the IOKit Patch because it says unknown md5 when running the XPS9530.sh so I manually ran the code in the .sh file.
Also while in panic mode I saw something about the IOKit

**Comment by 705369025wu** [comment]
![img_20151207_212206](https://cloud.githubusercontent.com/assets/11482336/11628221/428573ce-9d2b-11e5-838c-db5bcb14703b.jpg)
This is what happens with the original files

**Comment by the-darkvoid** [comment]
Looks more like a framebuffer configuration error then anything else. Check on the forums for more help with this.

**Comment by 705369025wu** [comment]
![img_20151208_194431](https://cloud.githubusercontent.com/assets/11482336/11655002/07b3b07a-9de5-11e5-9a52-9cbc0e309c4e.jpg)
![img_20151208_194439](https://cloud.githubusercontent.com/assets/11482336/11655008/16897cb0-9de5-11e5-9176-98ee4e49f7a6.jpg)
Changed the settings in BIOS to match the config.plist
Still same thing happens, just after more lines of logs in the verbose mode
Trying to check the forums, haven't found a match yet

**Comment by syscl** [comment]
You can try my script to patch the OS X. https://github.com/syscl/M3800 is both for XPS 9530 & M3800.
